rule("voidui.shaders")
    on_load(function (target)
        target:add("includedirs", path.join(target:autogendir(), "include"))
    end)
    before_build(function (target)
        import("core.project.config")
        import("core.project.depend")
        local slangc = config.get("slangc")
        if slangc then
            slangc = path.absolute(slangc)
        else
            local package = target:pkg("voidui-slang")
            slangc = path.join(package:installdir(), "bin", is_host("windows") and "slangc.exe" or "slangc")
        end
        assert(os.isfile(slangc), "Slang compiler not found: %s", slangc)
        local variant = target:is_plat("windows") and "dxbc" or (target:is_plat("macosx") and "msl" or "spirv")
        local outdir = path.join(target:autogendir(), "include", "voidui", "shaders")
        os.mkdir(outdir)
        for _, name in ipairs({"quad", "mask"}) do
            local source = path.absolute(path.join("shaders", name .. ".slang"))
            local header = path.join(outdir, name .. ".h")
            depend.on_changed(function ()
                print("compiling shader %s (%s)", name, variant)
                local body = {"// Generated by xmake/shaders.lua -- do not edit.\n#pragma once\n",
                              "#define VOIDUI_SHADER_" .. variant:upper() .. " 1\n",
                              "namespace voidui::shaders::" .. name .. " {\n"}
                for _, stage in ipairs({"vertex", "fragment"}) do
                    local output = path.join(outdir, name .. "." .. stage .. "." .. variant)
                    local args = {source, "-target", variant == "msl" and "metal" or variant,
                                  "-DVOIDUI_TARGET_" .. variant:upper(), "-entry", stage == "vertex" and "vs_main" or "fs_main",
                                  "-stage", stage, "-o", output}
                    if variant == "dxbc" then
                        table.join2(args, {"-profile", "sm_5_0"})
                    elseif variant == "spirv" then
                        table.join2(args, {"-fvk-use-entrypoint-name", "-fvk-invert-y"})
                    else
                        table.join2(args, {"-Wno-39029", "-Wno-39001"})
                    end
                    os.vrunv(slangc, args)
                    local data = io.readfile(output, {encoding = "binary"})
                    table.insert(body, string.format("alignas(4) inline constexpr unsigned char %s_%s[%d] = {\n", stage, variant, #data))
                    for offset = 1, #data, 16 do
                        local bytes = {}
                        for i = offset, math.min(offset + 15, #data) do
                            table.insert(bytes, string.format("0x%02x,", data:byte(i)))
                        end
                        table.insert(body, "    " .. table.concat(bytes) .. "\n")
                    end
                    table.insert(body, "};\n")
                end
                table.insert(body, "}\n")
                io.writefile(header, table.concat(body))
            end, {dependfile = target:dependfile(header),
                  files = {source, path.absolute("shaders/common.slang"), path.absolute("xmake/shaders.lua"), slangc},
                  values = {variant, slangc}, changed = target:is_rebuilt() or not os.isfile(header)})
        end
    end)
rule_end()
