# Script-mode helper: turns compiled shader artifacts into a C++ header.
#
# Invoked as:
#   cmake -DNAME=<ns> -DOUTPUT=<header> -DARTIFACTS=<a>;<b>;... -P BakeShaders.cmake
#
# Each artifact is "<variant>:<stage>:<path>", e.g. "dxil:vertex:/tmp/quad.vs.dxil".

set(_body "")
set(_variants "")

foreach(_artifact IN LISTS ARTIFACTS)
    string(REPLACE ":" ";" _parts "${_artifact}")
    list(GET _parts 0 _variant)
    list(GET _parts 1 _stage)
    list(SUBLIST _parts 2 -1 _path_parts)
    string(JOIN ":" _path ${_path_parts})

    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "BakeShaders: missing artifact '${_path}'")
    endif()

    file(READ "${_path}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _byte_count "${_hex_len} / 2")

    # "0a0b" -> "0x0a,0x0b,", wrapped so the generated lines stay readable.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " _bytes "${_bytes}")

    string(APPEND _body
        "alignas(4) inline constexpr unsigned char ${_stage}_${_variant}[${_byte_count}] = {\n    ${_bytes}\n};\n\n")
    list(APPEND _variants "${_variant}")
endforeach()

list(REMOVE_DUPLICATES _variants)

set(_defines "")
foreach(_variant IN LISTS _variants)
    string(TOUPPER "${_variant}" _upper)
    string(APPEND _defines "#define VOIDUI_SHADER_${_upper} 1\n")
endforeach()

file(WRITE "${OUTPUT}"
"// Generated by cmake/BakeShaders.cmake -- do not edit.\n"
"#pragma once\n\n"
"${_defines}\n"
"namespace voidui::shaders::${NAME} {\n\n"
"${_body}"
"} // namespace voidui::shaders::${NAME}\n")
